
export const Partidos = {
    AVANTE : "./../../assets/Imagens/partidos/avante.png",
    CIDADANIA: "./../../assets/Imagens/partidos/Cidadania.png",
    DEM:"./../../assets/Imagens/partidos/democratas.png",
    MDB:"./../../assets/Imagens/partidos/mdb.png",
    NOVO:"./../../assets/Imagens/partidos/novo.png",
    PATRI:"./../../assets/Imagens/partidos/patriota.png.png",
    PATRIOTA:"./../../assets/Imagens/partidos/patriota.png",
    PCB:"./../../assets/Imagens/partidos/pcb.png",
    PCdoB:"./../../assets/Imagens/partidos/pcdob.png",
    PCO:"./../../assets/Imagens/partidos/pco.png",
    PDT:"./../../assets/Imagens/partidos/PDT.png",
    PHS:"./../../assets/Imagens/partidos/phs.png",
    PL:"./../../assets/Imagens/partidos/pl.png",
    PMB:"./../../assets/Imagens/partidos/Pmb.png",
    PMN:"./../../assets/Imagens/partidos/pmn.png",
    PODE:"./../../assets/Imagens/partidos/podemos.png",
    PP:"./../../assets/Imagens/partidos/pp.png",
    PPL:"./../../assets/Imagens/partidos/ppl.png",
    PPS:"./../../assets/Imagens/partidos/pps.png",
    PR:"./../../assets/Imagens/partidos/pl.png",
    PRB:"./../../assets/Imagens/partidos/prb.png",
    PROS:"./../../assets/Imagens/partidos/pros.png",
    PRP:"./../../assets/Imagens/partidos/prp.png",
    PRTB:"./../../assets/Imagens/partidos/prtb.png",
    PSB:"./../../assets/Imagens/partidos/psb.png",
    PSC:"./../../assets/Imagens/partidos/psc.png",
    PSD:"./../../assets/Imagens/partidos/psd.png",
    PSDB:"./../../assets/Imagens/partidos/psdb.png",
    PSL:"./../../assets/Imagens/partidos/psl.png",
    PSOL:"./../../assets/Imagens/partidos/psol.png",
    PSTU:"./../../assets/Imagens/partidos/pstu.png",
    PT:"./../../assets/Imagens/partidos/pt.png",
    PTB:"./../../assets/Imagens/partidos/ptb.png",
    PTC:"./../../assets/Imagens/partidos/ptc.png",
    PV:"./../../assets/Imagens/partidos/pv.png",
    REDE:"./../../assets/Imagens/partidos/avante.png",
    REPUBLICANOS:"./../../assets/Imagens/partidos/prb.png",
    'S.PART':"./../../assets/Imagens/partidos/sp.png",
    SOLIDARIEDADE:"./../../assets/Imagens/partidos/solidariedade.png",
    UNIÃO:"./../../assets/Imagens/partidos/uniao.png",
}